export default {
    PRIM: 'Prim',
    SEC: 'Sec',
    TERT: 'Tert',
    ADD: 'add',
    EDIT: 'edit',
    DUP: 'dup',
    TWO_WINDING: 'Two-winding',
    THREE_WINDING: 'Three-winding',
    WITH_TERT : 'Auto w/ tert',
    WITHOUT_TERT : 'Auto w/o tert',
    GOOD : 'Good',
    FAIR : 'Fair',
    POOR : 'Poor',
    BAD : 'Bad',
}